//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход гостя.
    /// </summary>
    // *** Start programmer edit section *** (ВходГостя CustomAttributes)

    // *** End programmer edit section *** (ВходГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Вход гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходГостяE", new string[] {
            "Гость as \'Гость\'",
            "Гость.РегистрацКлюча.НомерКлюча as \'Карта\'",
            "Гость.РегистрацКлюча.Комната.НомерКомнаты as \'Комната\'"})]
    [MasterViewDefineAttribute("ВходГостяE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ВходГостя : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.KursovayaRabota.Гость fГость;
        
        private IIS.KursovayaRabota.ВходВНомер fВходВНомер;
        
        // *** Start programmer edit section *** (ВходГостя CustomMembers)

        // *** End programmer edit section *** (ВходГостя CustomMembers)

        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.Гость CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Get start)

                // *** End programmer edit section *** (ВходГостя.Гость Get start)
                IIS.KursovayaRabota.Гость result = this.fГость;
                // *** Start programmer edit section *** (ВходГостя.Гость Get end)

                // *** End programmer edit section *** (ВходГостя.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Set start)

                // *** End programmer edit section *** (ВходГостя.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ВходГостя.Гость Set end)

                // *** End programmer edit section *** (ВходГостя.Гость Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KursovayaRabota.ВходВНомер.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.ВходВНомер CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.ВходВНомер CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ВходВНомер"})]
        public virtual IIS.KursovayaRabota.ВходВНомер ВходВНомер
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.ВходВНомер Get start)

                // *** End programmer edit section *** (ВходГостя.ВходВНомер Get start)
                IIS.KursovayaRabota.ВходВНомер result = this.fВходВНомер;
                // *** Start programmer edit section *** (ВходГостя.ВходВНомер Get end)

                // *** End programmer edit section *** (ВходГостя.ВходВНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.ВходВНомер Set start)

                // *** End programmer edit section *** (ВходГостя.ВходВНомер Set start)
                this.fВходВНомер = value;
                // *** Start programmer edit section *** (ВходГостя.ВходВНомер Set end)

                // *** End programmer edit section *** (ВходГостя.ВходВНомер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходГостяE", typeof(IIS.KursovayaRabota.ВходГостя));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходГостя.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)
    public class DetailArrayOfВходГостя : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KursovayaRabota.DetailArrayOfВходГостя members)

        // *** End programmer edit section *** (IIS.KursovayaRabota.DetailArrayOfВходГостя members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходГостя by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходГостя.
        /// </summary>
        public DetailArrayOfВходГостя(IIS.KursovayaRabota.ВходВНомер fВходВНомер) : 
                base(typeof(ВходГостя), ((ICSSoft.STORMNET.DataObject)(fВходВНомер)))
        {
        }
        
        public IIS.KursovayaRabota.ВходГостя this[int index]
        {
            get
            {
                return ((IIS.KursovayaRabota.ВходГостя)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KursovayaRabota.ВходГостя dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
