//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистрац входа.
    /// </summary>
    // *** Start programmer edit section *** (ВходВНомер CustomAttributes)

    // *** End programmer edit section *** (ВходВНомер CustomAttributes)
    [AutoAltered()]
    [Caption("Вход в номер")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходВНомерE", new string[] {
            "Дата as \'Дата\'"})]
    [AssociatedDetailViewAttribute("ВходВНомерE", "ВходГостя", "ВходГостяE", true, "", "Вход гостя", true, new string[] {
            ""})]
    [View("ВходВНомерL", new string[] {
            "Дата as \'Дата\'"})]
    public class ВходВНомер : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.KursovayaRabota.DetailArrayOfВходГостя fВходГостя;
        
        // *** Start programmer edit section *** (ВходВНомер CustomMembers)

        // *** End programmer edit section *** (ВходВНомер CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ВходВНомер.Дата CustomAttributes)

        // *** End programmer edit section *** (ВходВНомер.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ВходВНомер.Дата Get start)

                // *** End programmer edit section *** (ВходВНомер.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ВходВНомер.Дата Get end)

                // *** End programmer edit section *** (ВходВНомер.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходВНомер.Дата Set start)

                // *** End programmer edit section *** (ВходВНомер.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ВходВНомер.Дата Set end)

                // *** End programmer edit section *** (ВходВНомер.Дата Set end)
            }
        }
        
        /// <summary>
        /// Регистрац входа.
        /// </summary>
        // *** Start programmer edit section *** (ВходВНомер.ВходГостя CustomAttributes)

        // *** End programmer edit section *** (ВходВНомер.ВходГостя CustomAttributes)
        public virtual IIS.KursovayaRabota.DetailArrayOfВходГостя ВходГостя
        {
            get
            {
                // *** Start programmer edit section *** (ВходВНомер.ВходГостя Get start)

                // *** End programmer edit section *** (ВходВНомер.ВходГостя Get start)
                if ((this.fВходГостя == null))
                {
                    this.fВходГостя = new IIS.KursovayaRabota.DetailArrayOfВходГостя(this);
                }
                IIS.KursovayaRabota.DetailArrayOfВходГостя result = this.fВходГостя;
                // *** Start programmer edit section *** (ВходВНомер.ВходГостя Get end)

                // *** End programmer edit section *** (ВходВНомер.ВходГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходВНомер.ВходГостя Set start)

                // *** End programmer edit section *** (ВходВНомер.ВходГостя Set start)
                this.fВходГостя = value;
                // *** Start programmer edit section *** (ВходВНомер.ВходГостя Set end)

                // *** End programmer edit section *** (ВходВНомер.ВходГостя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходВНомерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходВНомерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходВНомерE", typeof(IIS.KursovayaRabota.ВходВНомер));
                }
            }
            
            /// <summary>
            /// "ВходВНомерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходВНомерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходВНомерL", typeof(IIS.KursovayaRabota.ВходВНомер));
                }
            }
        }
    }
}
