//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гость.
    /// </summary>
    // *** Start programmer edit section *** (Гость CustomAttributes)

    // *** End programmer edit section *** (Гость CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостьE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "ДанныеПаспорта as \'Серия и номер паспорта\'",
            "Телефон as \'Телефон\'",
            "Почта as \'E-mail\'",
            "РегистрацКлюча as \'Номер ключа\'"})]
    [MasterViewDefineAttribute("ГостьE", "РегистрацКлюча", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКлюча")]
    [View("ГостьL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "ДанныеПаспорта as \'Серия и номер паспорта\'",
            "Телефон as \'Телефон\'",
            "Почта as \'E-mail\'",
            "РегистрацКлюча.НомерКлюча as \'Номер ключа\'"})]
    public class Гость : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private int fДанныеПаспорта;
        
        private int fТелефон;
        
        private string fПочта;
        
        private IIS.KursovayaRabota.РегистрацКлюча fРегистрацКлюча;
        
        // *** Start programmer edit section *** (Гость CustomMembers)

        // *** End programmer edit section *** (Гость CustomMembers)

        
        /// <summary>
        /// ДанныеПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ДанныеПаспорта CustomAttributes)

        // *** End programmer edit section *** (Гость.ДанныеПаспорта CustomAttributes)
        public virtual int ДанныеПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Get start)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Get start)
                int result = this.fДанныеПаспорта;
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Get end)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Set start)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Set start)
                this.fДанныеПаспорта = value;
                // *** Start programmer edit section *** (Гость.ДанныеПаспорта Set end)

                // *** End programmer edit section *** (Гость.ДанныеПаспорта Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Гость.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Get start)

                // *** End programmer edit section *** (Гость.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Гость.ДатаРождения Get end)

                // *** End programmer edit section *** (Гость.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ДатаРождения Set start)

                // *** End programmer edit section *** (Гость.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Гость.ДатаРождения Set end)

                // *** End programmer edit section *** (Гость.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Почта CustomAttributes)

        // *** End programmer edit section *** (Гость.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Почта Get start)

                // *** End programmer edit section *** (Гость.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (Гость.Почта Get end)

                // *** End programmer edit section *** (Гость.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Почта Set start)

                // *** End programmer edit section *** (Гость.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (Гость.Почта Set end)

                // *** End programmer edit section *** (Гость.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Гость.Телефон CustomAttributes)

        // *** End programmer edit section *** (Гость.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Гость.Телефон Get start)

                // *** End programmer edit section *** (Гость.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Гость.Телефон Get end)

                // *** End programmer edit section *** (Гость.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.Телефон Set start)

                // *** End programmer edit section *** (Гость.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Гость.Телефон Set end)

                // *** End programmer edit section *** (Гость.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Гость.ФИО CustomAttributes)

        // *** End programmer edit section *** (Гость.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Гость.ФИО Get start)

                // *** End programmer edit section *** (Гость.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Гость.ФИО Get end)

                // *** End programmer edit section *** (Гость.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.ФИО Set start)

                // *** End programmer edit section *** (Гость.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Гость.ФИО Set end)

                // *** End programmer edit section *** (Гость.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Гость.
        /// </summary>
        // *** Start programmer edit section *** (Гость.РегистрацКлюча CustomAttributes)

        // *** End programmer edit section *** (Гость.РегистрацКлюча CustomAttributes)
        [PropertyStorage(new string[] {
                "РегистрацКлюча"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.РегистрацКлюча РегистрацКлюча
        {
            get
            {
                // *** Start programmer edit section *** (Гость.РегистрацКлюча Get start)

                // *** End programmer edit section *** (Гость.РегистрацКлюча Get start)
                IIS.KursovayaRabota.РегистрацКлюча result = this.fРегистрацКлюча;
                // *** Start programmer edit section *** (Гость.РегистрацКлюча Get end)

                // *** End programmer edit section *** (Гость.РегистрацКлюча Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гость.РегистрацКлюча Set start)

                // *** End programmer edit section *** (Гость.РегистрацКлюча Set start)
                this.fРегистрацКлюча = value;
                // *** Start programmer edit section *** (Гость.РегистрацКлюча Set end)

                // *** End programmer edit section *** (Гость.РегистрацКлюча Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьE", typeof(IIS.KursovayaRabota.Гость));
                }
            }
            
            /// <summary>
            /// "ГостьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостьL", typeof(IIS.KursovayaRabota.Гость));
                }
            }
        }
    }
}
