//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карта.
    /// </summary>
    // *** Start programmer edit section *** (Карта CustomAttributes)

    // *** End programmer edit section *** (Карта CustomAttributes)
    [AutoAltered()]
    [Caption("Карты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартаE", new string[] {
            "НомерКарты as \'Номер карты\'"})]
    [View("КартаL", new string[] {
            "НомерКарты as \'Номер карты\'"})]
    public class Карта : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        // *** Start programmer edit section *** (Карта CustomMembers)

        // *** End programmer edit section *** (Карта CustomMembers)

        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (Карта.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (Карта.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (Карта.НомерКарты Get start)

                // *** End programmer edit section *** (Карта.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (Карта.НомерКарты Get end)

                // *** End programmer edit section *** (Карта.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Карта.НомерКарты Set start)

                // *** End programmer edit section *** (Карта.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (Карта.НомерКарты Set end)

                // *** End programmer edit section *** (Карта.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартаE", typeof(IIS.KursovayaRabota.Карта));
                }
            }
            
            /// <summary>
            /// "КартаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартаL", typeof(IIS.KursovayaRabota.Карта));
                }
            }
        }
    }
}
