//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// РегистрацКлюча.
    /// </summary>
    // *** Start programmer edit section *** (РегистрацКлюча CustomAttributes)

    // *** End programmer edit section *** (РегистрацКлюча CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрацКлючаE", new string[] {
            "Дата as \'Дата\'",
            "НомерКлюча as \'Ключ\'",
            "Комната as \'Номер комнаты\'",
            "Карта as \'Номер карты\'",
            "Считыватель as \'Уникальный код\'",
            "СрокДействия as \'Карта действует до:\'",
            "Сотрудник as \'Ответственный\'"})]
    [MasterViewDefineAttribute("РегистрацКлючаE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКомнаты")]
    [MasterViewDefineAttribute("РегистрацКлючаE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКарты")]
    [MasterViewDefineAttribute("РегистрацКлючаE", "Считыватель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "УникальныйКод")]
    [MasterViewDefineAttribute("РегистрацКлючаE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("РегистрацКлючаL", new string[] {
            "Дата as \'Дата\'",
            "НомерКлюча as \'Ключ\'",
            "Комната.НомерКомнаты as \'Номер комнаты\'",
            "Карта.НомерКарты as \'Номер карты\'",
            "Считыватель.УникальныйКод as \'Уникальный код\'",
            "СрокДействия as \'Карта действует до:\'",
            "Сотрудник.ФИО as \'Ответственный\'"})]
    public class РегистрацКлюча : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private System.DateTime fСрокДействия;
        
        private int fНомерКлюча;
        
        private IIS.KursovayaRabota.Карта fКарта;
        
        private IIS.KursovayaRabota.Сотрудник fСотрудник;
        
        private IIS.KursovayaRabota.Считыватель fСчитыватель;
        
        private IIS.KursovayaRabota.Комната fКомната;
        
        // *** Start programmer edit section *** (РегистрацКлюча CustomMembers)

        // *** End programmer edit section *** (РегистрацКлюча CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Дата Get start)

                // *** End programmer edit section *** (РегистрацКлюча.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрацКлюча.Дата Get end)

                // *** End programmer edit section *** (РегистрацКлюча.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Дата Set start)

                // *** End programmer edit section *** (РегистрацКлюча.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрацКлюча.Дата Set end)

                // *** End programmer edit section *** (РегистрацКлюча.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерКлюча.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.НомерКлюча CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.НомерКлюча CustomAttributes)
        public virtual int НомерКлюча
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.НомерКлюча Get start)

                // *** End programmer edit section *** (РегистрацКлюча.НомерКлюча Get start)
                int result = this.fНомерКлюча;
                // *** Start programmer edit section *** (РегистрацКлюча.НомерКлюча Get end)

                // *** End programmer edit section *** (РегистрацКлюча.НомерКлюча Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.НомерКлюча Set start)

                // *** End programmer edit section *** (РегистрацКлюча.НомерКлюча Set start)
                this.fНомерКлюча = value;
                // *** Start programmer edit section *** (РегистрацКлюча.НомерКлюча Set end)

                // *** End programmer edit section *** (РегистрацКлюча.НомерКлюча Set end)
            }
        }
        
        /// <summary>
        /// СрокДействия.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.СрокДействия CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.СрокДействия CustomAttributes)
        public virtual System.DateTime СрокДействия
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.СрокДействия Get start)

                // *** End programmer edit section *** (РегистрацКлюча.СрокДействия Get start)
                System.DateTime result = this.fСрокДействия;
                // *** Start programmer edit section *** (РегистрацКлюча.СрокДействия Get end)

                // *** End programmer edit section *** (РегистрацКлюча.СрокДействия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.СрокДействия Set start)

                // *** End programmer edit section *** (РегистрацКлюча.СрокДействия Set start)
                this.fСрокДействия = value;
                // *** Start programmer edit section *** (РегистрацКлюча.СрокДействия Set end)

                // *** End programmer edit section *** (РегистрацКлюча.СрокДействия Set end)
            }
        }
        
        /// <summary>
        /// РегистрацКлюча.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.Карта CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Карта Get start)

                // *** End programmer edit section *** (РегистрацКлюча.Карта Get start)
                IIS.KursovayaRabota.Карта result = this.fКарта;
                // *** Start programmer edit section *** (РегистрацКлюча.Карта Get end)

                // *** End programmer edit section *** (РегистрацКлюча.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Карта Set start)

                // *** End programmer edit section *** (РегистрацКлюча.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (РегистрацКлюча.Карта Set end)

                // *** End programmer edit section *** (РегистрацКлюча.Карта Set end)
            }
        }
        
        /// <summary>
        /// РегистрацКлюча.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.Комната CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Комната Get start)

                // *** End programmer edit section *** (РегистрацКлюча.Комната Get start)
                IIS.KursovayaRabota.Комната result = this.fКомната;
                // *** Start programmer edit section *** (РегистрацКлюча.Комната Get end)

                // *** End programmer edit section *** (РегистрацКлюча.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Комната Set start)

                // *** End programmer edit section *** (РегистрацКлюча.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (РегистрацКлюча.Комната Set end)

                // *** End programmer edit section *** (РегистрацКлюча.Комната Set end)
            }
        }
        
        /// <summary>
        /// РегистрацКлюча.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Сотрудник Get start)

                // *** End programmer edit section *** (РегистрацКлюча.Сотрудник Get start)
                IIS.KursovayaRabota.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (РегистрацКлюча.Сотрудник Get end)

                // *** End programmer edit section *** (РегистрацКлюча.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Сотрудник Set start)

                // *** End programmer edit section *** (РегистрацКлюча.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (РегистрацКлюча.Сотрудник Set end)

                // *** End programmer edit section *** (РегистрацКлюча.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// РегистрацКлюча.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацКлюча.Считыватель CustomAttributes)

        // *** End programmer edit section *** (РегистрацКлюча.Считыватель CustomAttributes)
        [PropertyStorage(new string[] {
                "Считыватель"})]
        [NotNull()]
        public virtual IIS.KursovayaRabota.Считыватель Считыватель
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Считыватель Get start)

                // *** End programmer edit section *** (РегистрацКлюча.Считыватель Get start)
                IIS.KursovayaRabota.Считыватель result = this.fСчитыватель;
                // *** Start programmer edit section *** (РегистрацКлюча.Считыватель Get end)

                // *** End programmer edit section *** (РегистрацКлюча.Считыватель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацКлюча.Считыватель Set start)

                // *** End programmer edit section *** (РегистрацКлюча.Считыватель Set start)
                this.fСчитыватель = value;
                // *** Start programmer edit section *** (РегистрацКлюча.Считыватель Set end)

                // *** End programmer edit section *** (РегистрацКлюча.Считыватель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрацКлючаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрацКлючаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрацКлючаE", typeof(IIS.KursovayaRabota.РегистрацКлюча));
                }
            }
            
            /// <summary>
            /// "РегистрацКлючаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрацКлючаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрацКлючаL", typeof(IIS.KursovayaRabota.РегистрацКлюча));
                }
            }
        }
    }
}
