//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabota
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Считыватель.
    /// </summary>
    // *** Start programmer edit section *** (Считыватель CustomAttributes)

    // *** End programmer edit section *** (Считыватель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СчитывательE", new string[] {
            "УникальныйКод as \'Уникальный код\'"})]
    [View("СчитывательL", new string[] {
            "УникальныйКод as \'Уникальный код\'"})]
    public class Считыватель : ICSSoft.STORMNET.DataObject
    {
        
        private string fУникальныйКод;
        
        // *** Start programmer edit section *** (Считыватель CustomMembers)

        // *** End programmer edit section *** (Считыватель CustomMembers)

        
        /// <summary>
        /// УникальныйКод.
        /// </summary>
        // *** Start programmer edit section *** (Считыватель.УникальныйКод CustomAttributes)

        // *** End programmer edit section *** (Считыватель.УникальныйКод CustomAttributes)
        [StrLen(255)]
        public virtual string УникальныйКод
        {
            get
            {
                // *** Start programmer edit section *** (Считыватель.УникальныйКод Get start)

                // *** End programmer edit section *** (Считыватель.УникальныйКод Get start)
                string result = this.fУникальныйКод;
                // *** Start programmer edit section *** (Считыватель.УникальныйКод Get end)

                // *** End programmer edit section *** (Считыватель.УникальныйКод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Считыватель.УникальныйКод Set start)

                // *** End programmer edit section *** (Считыватель.УникальныйКод Set start)
                this.fУникальныйКод = value;
                // *** Start programmer edit section *** (Считыватель.УникальныйКод Set end)

                // *** End programmer edit section *** (Считыватель.УникальныйКод Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СчитывательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчитывательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчитывательE", typeof(IIS.KursovayaRabota.Считыватель));
                }
            }
            
            /// <summary>
            /// "СчитывательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчитывательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчитывательL", typeof(IIS.KursovayaRabota.Считыватель));
                }
            }
        }
    }
}
